# Dockerfile to produce the production ITS_LIVE docker image for datacube

# FROM centos:8
FROM continuumio/miniconda3:4.9.2

# Set an encoding to make things work smoothly
ENV LANG en_US.UTF-8

# files are copied from this dir on the host to the docker image
ARG SOURCE_DIR

# build params used for the docker labels
ARG BUILD_DATE_TIME
ARG BUILD_VERSION

# labels (overwrite the labels inherited from the base image)
# the label-schema convention: http://label-schema.org/rc1/
LABEL org.opencontainers.image.title="ITS_LIVE Data Cube"
LABEL org.opencontainers.image.description="ITS_LIVE data cube for image pair velocities"
LABEL org.opencontainers.image.source="https://github.com/nasa-jpl/itslive"
LABEL org.opencontainers.image.version=${BUILD_VERSION}
LABEL org.opencontainers.image.created=${BUILD_DATE_TIME}
LABEL org.opencontainers.image.vendor="NASA Jet Propulsion Laboratory (JPL), California Institute of Technology"
LABEL org.opencontainers.image.authors="ITS_LIVE, a NASA MEaSUREs project (its-live.jpl.nasa.gov)"
LABEL org.opencontainers.image.licenses="MIT"

# create user
ARG CONDA_UID=1000
ARG CONDA_GID=1000
RUN groupadd -g "${CONDA_GID}" --system conda && \
    useradd -l -u "${CONDA_UID}" -g "${CONDA_GID}" --system -d /home/conda -m  -s /bin/bash conda && \
    conda update -n base -c defaults conda && \
    chown -R conda:conda /opt && \
    conda clean -afy && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> /home/conda/.profile && \
    echo "conda activate base" >> /home/conda/.profile

USER ${CONDA_UID}
SHELL ["/bin/bash", "-l", "-c"]
WORKDIR /home/conda

# copy the  software and other files
COPY --chown=1000:1000 ${SOURCE_DIR} /home/conda/itslive
#COPY conda-env.yml /home/conda/conda-env.yml

RUN conda env create -f itslive/cube_environment.yml && \
    conda clean -afy && \
    conda activate itscube && \
    sed -i 's/conda activate base/conda activate itscube/g' /home/conda/.profile

# Set directory and entrypoint
WORKDIR /home/conda/itslive
ENTRYPOINT ["/home/conda/itslive/entrypoint_cube.sh"]
